env:
  es6: true
  browser: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: 6
  sourceType: module
  
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never