name: lint
on:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install depecencies
      run: npm install

    - name: lint
      run: npm run lint